### ISSUE TITLE
GHC 8.4 support?

### ISSUE THREAD

**Issue by kozross** [hedgehogqa/haskell-hedgehog-classes#22]
Currently, all versions of ``hedgehog-classes`` require ``base >= 4.12``. Is there something specific in that version of ``base`` that you need to make ``hedgehog-classes`` tick?

**Comment by chessai** [comment]
Yes: quantified-constraints.

QCs are much cleaner than Eq1/Show1 etc. I also maintain quickcheck-classes, where we allow GHC versions >= 7.4 due to it being a part of primitive's test suite. Seeing as this library has no such burden, I saw it easier to just stick with 8.6. Allowing older versions of GHC is something I would be okay with doing (no older than 8.4), and would take a PR for, but I myself am unwilling to do the work to make that change anytime soon. That being said, GHC 8.10 is not far away, and at that point we'll have 8.6,8.8,and 8.10, so I'd be looking to remove support for GHC <= 8.4 eventually.

I'll take a PR in the meantime, and i'll cross the remaining bridges when i get to them.

**Comment by kozross** [comment]
@chessai I see. I'm willing to give it a go, but I'd need to read up on how all this stuff is implemented in more detail first. Might be a while.

**Comment by chessai** [comment]
The only real difference would be changing occurrences of QCs with Eq{1|2} or Show{1|2} and the necessary methods.

for example:

```haskell
withQC :: (forall x. Eq x => Eq (f x), forall x. Show x => Show (f x)) => ...

withoutQC :: (Eq1 f, Show1 f) => ...
```

Similarly for Eq2. Im the situation with QCs you can just use `(==)`/`show` everywhere, but without them you have to use liftEq1/liftShowsPrec etc.

It's mostly a bunch of CPP and tedium.

**Comment by kozross** [comment]
@chessai If that's all it is, I might be able to get that done fairly rapidly. I'll see if I can get you PR by the end of the weekend.

**Comment by chessai** [comment]
Sounds great, thanks! I'll need to add ci to make such an addition easier to maintain.

**Comment by kozross** [comment]
Before I go any further, I wanted to ask - what is your policy on HLint suggestions? I'm currently editing ``Hedgehog.Classes.Alternative``, and I'm getting HLint suggestions for: ``let lhs = empty <|> a``, ``let lhs = a <|> empty``, and the whole do-block inside the ``alternativeAssociativity`` method. Should I apply these, or leave as-are?

**Comment by chessai** [comment]
I don't like hlint suggestions. Especially here: The code formatting was for readability, since all the function bodies are very uniform. I very much appreciate you asking!

**Comment by kozross** [comment]
@chessai OK, I'll not apply those then.

**Comment by kozross** [comment]
I've hit a bit of a snag. After a lot of CPP-and-tedium style find-and-replace, I get errors like this one:

```
src/Hedgehog/Classes/Category.hs:133:8: error:
    • Could not deduce (Show (f Integer Integer))
        arising from a use of ‘forAll’
      from the context: (Category f, Eq2 f, Show2 f)
        bound by the type signature for:
                   categoryCommutativity :: forall (f :: * -> * -> *).
                                            (Category f, Eq2 f, Show2 f) =>
                                            (forall x y. Gen x -> Gen y -> Gen (f x y)) -> Property
        at src/Hedgehog/Classes/Category.hs:(126,1)-(130,62)
    • In a stmt of a 'do' block:
        f <- forAll $ fgen genSmallInteger genSmallInteger
      In the second argument of ‘($)’, namely
        ‘do f <- forAll $ fgen genSmallInteger genSmallInteger
            g <- forAll $ fgen genSmallInteger genSmallInteger
            (f . g) `heq2` (g . f)’
      In the expression:
        property
          $ do f <- forAll $ fgen genSmallInteger genSmallInteger
               g <- forAll $ fgen genSmallInteger genSmallInteger
               (f . g) `heq2` (g . f)
```

How do I write around that?

**Comment by chessai** [comment]
How have you redefined heq2?

**Comment by chessai** [comment]
Oh, your heq2 is fine. It's forAll.
I think you have to switch occurences of forAll to `forAllWith`?

**Comment by kozross** [comment]
@chessai It seems this will be trickier than it first looks. One of the nice aspects of ``QuantifiedConstraints`` is that they're transitive to any number of 'levels'. I'm already running into pain points with something like ``Hedgehog.Classes.Bitraversable``, where I need ghastly munges like this:

```haskell
-- deep in the guts of bitraversableNaturality
, lawContextReduced = reducedWith (($ "") . liftShowsPrec (liftShowsPrec2 showsPrec showList showsPrec showList)
                                                                  (liftShowList2 showsPrec showList showsPrec showList) 0) lhs rhs
```
The very next line is similarly problematic, due to how ``heqCtx1`` is defined: even with ``lift*`` from the assorted classes at play, the lift is only one level deep, whereas here, it seems to need several.

**Comment by chessai** [comment]
I am out and about right now, but you may want to take a look at
quickcheck-classes, which does support what you're looking for.

**Comment by chessai** [comment]
@kozross is there anything holding you up that i can help with?

**Comment by chessai** [comment]
No longer worth it AFAICT, 8.4 is getting older and older. Let me know if you think otherwise.

Thanks for your efforts up to this point.
