### ISSUE TITLE
Request: Add to stackage

### ISSUE THREAD

**Issue by psibi** [hedgehogqa/haskell-hedgehog-classes#34]
Would the author of the package be interested to add this to Stackage ?

Currently, I'm planning to add this as one of the dependency in my package and observed that this isn't part of stackage.

I can volunteer to add/maintain this in Stackage in case the author doesn't want to do it. But it's best if the author does that so as to do update necessary version constraints and release a package when it's needed (based on lts, nightly changes)

**Comment by chessai** [comment]
I can do it, that's a good idea

**Comment by chessai** [comment]
https://github.com/commercialhaskell/stackage/pull/5577
