### ISSUE TITLE
Make a Hackage release

### ISSUE THREAD

**Issue by chshersh** [hedgehogqa/haskell-hedgehog-classes#46]
Hi everyone 👋🏻 

Thanks for maintaining this package! 🙏🏻 

Would be possible to release the latest version of `hedgehog-classes` to Hackage? The current main branch contains some bugfixes not yet released that I submitted almost a year ago and I'd really appreciate a Hackage release! 🏆 

I'm using `hedgehog-classes` in a Haskell course and not depending on a GitHub fork would make the UX much better for newcomers!

* https://github.com/haskell-beginners-2022/exercises/issues/79

I understand that you're all volunteers but I want to say that I'd really appreciate a release 😌 Thanks!

**Comment by chessai** [comment]
I would like to, if #45 is fixed

**Comment by chessai** [comment]
Now, #48. Don't want to make a release with incomplete #47

**Comment by chessai** [comment]
Published at 0.2.5.4

**Comment by chshersh** [comment]
@chessai Thanks a lot for your work!
